# yamllint --format github .github/workflows/test.yml
---
name: test webmvc4-boot

on:
  # We deploy non-tagged pushes to master relevant for this project. We can't opt out of
  # documentation-only commits because GH actions does not permit paths and paths-ignore.
  pull_request:
    branches: master
    paths:
      - "build-bin/**"
      - "docker/**"
      - "webmvc4-boot/**"
      - ".github/workflows/test-webmvc4-boot.yaml"
      - "parent-pom.xml"

jobs:
  test:
    runs-on: ubuntu-22.04  # newest available distribution, aka jellyfish
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ./m2repository  # Shared with the Docker build context via .dockerignore
          key: ${{ runner.os }}-webmvc4-boot-maven-${{ hashFiles('parent-pom.xml', 'webmvc4-boot/pom.xml') }}
          restore-keys: ${{ runner.os }}-webmvc4-boot-maven-
      # Don't attempt to cache Docker. Sensitive information can be stolen
      # via forks, and login session ends up in ~/.docker. This is ok because
      # we publish DOCKER_PARENT_IMAGE to ghcr.io, hence local to the runner.
      - name: Test webmvc4-boot
        run: |
          build-bin/configure_test webmvc4-boot &&
          build-bin/test webmvc4-boot
